import Link from 'next/link';
import { BrandMark, PlayButton, SiteFooter } from '../components/MarketingUi';
import { seoPageMetadata } from '../site-config';

export const metadata = seoPageMetadata('/about', 'About Nexal & Our Fitness Guides', 'Learn who publishes Nexal fitness guides, how to use the examples, the limits of AI planning and how to contact the product team.');

export default function AboutPage() {
  return <main><nav className="nav shell" aria-label="Main navigation"><Link href="/" aria-label="Nexal home"><BrandMark /></Link><PlayButton compact placement="about_nav" /></nav><div className="legal-page"><article className="legal-shell"><span className="section-kicker">ABOUT NEXAL</span><h1>Tools for your routine.<br />Clarity about the details.</h1><p>Nexal is an Android fitness app that brings workout and nutrition records together. This website introduces the app and publishes practical guides for people deciding how to plan and track their routine.</p><section><h2>What Nexal offers</h2><p>Core manual workout logging, custom workouts, workout history and manual meal, calorie and macro tracking are free. Optional Premium features include AI workout and meal planning, AI macro estimates and barcode scanning. Check the current Google Play listing and in-app checkout for availability, local prices and eligible offers.</p><p><Link href="/workout-meal-planner-app">Explore workout and meal tracking</Link> or <Link href="/guides">browse the fitness guides</Link>.</p></section><section id="editorial-policy"><h2>Who writes the guides?</h2><p>The guides are Nexal product-team content, prepared with AI assistance. They are not independent reviews, professional coaching or clinically reviewed nutrition advice. Their purpose is to explain app selection, everyday record keeping and the difference between planning and logging.</p><p>Examples use illustrative records and quantities, not customer results or personal prescriptions. External references are linked where they support an explanation. Product claims should distinguish free tracking from paid AI tools; no guide promises a particular health outcome or rate of progress.</p><p>Publication dates appear on individual guides. Dates are not refreshed merely to make a page look new. Feature availability can change, so verify important purchase details in the app and Google Play before subscribing.</p></section><section><h2>Use AI output with judgement</h2><p>Generated workout plans and food estimates can contain mistakes. Review exercises, equipment, ingredients, quantities and assumptions before acting. AI does not supervise technique, diagnose a condition or establish whether a programme is suitable for you. Seek qualified individual advice when needed.</p></section><section><h2>Corrections and support</h2><p>If a guide is unclear or a feature description no longer matches the app, email <a href="mailto:support@nexal.app">support@nexal.app</a> with the page address and the point that needs checking. Do not send medical records or payment credentials.</p><p>For account information and deletion requests, read the <Link href="/privacy">Nexal privacy policy</Link>.</p></section></article></div><SiteFooter /></main>;
}
