import { appSchema, websiteSchema } from './site-config';
import { BrandMark, PlayButton, SiteFooter } from './components/MarketingUi';

function PhonePreview() {
  return <div className="phone-wrap" role="img" aria-label="Illustrative Nexal Android dashboard showing daily calories, protein, an AI workout plan and weekly progress">
    <div className="orbit orbit-one" /><div className="orbit orbit-two" />
    <div className="phone"><div className="phone-island" /><div className="phone-screen">
      <div className="app-topline"><div><span>GOOD MORNING</span><strong>Ready to move?</strong></div><i>N</i></div>
      <div className="daily-score"><div className="ring"><b>72</b><span>score</span></div><div><small>TODAY&apos;S PROGRESS</small><h3>On track</h3><p>1,640 of 2,200 kcal</p></div></div>
      <div className="mini-stats"><div><span>PROTEIN</span><strong>124g</strong><i style={{ "--fill": "82%" } as React.CSSProperties} /></div><div><span>STEPS</span><strong>7,842</strong><i style={{ "--fill": "67%" } as React.CSSProperties} /></div></div>
      <div className="next-card"><span>NEXT UP · AI WORKOUT</span><div><strong>Upper body strength</strong><b>32 min</b></div><p>6 exercises · Intermediate</p><button aria-label="Start workout">Start workout <em>→</em></button></div>
      <div className="week-bars" aria-hidden="true">{[48,70,55,88,64,82,76].map((height,index)=><div key={index}><i style={{height:`${height}%`}} /><span>{"SMTWTFS"[index]}</span></div>)}</div>
    </div></div>
    <div className="float-card float-meal"><i>✓</i><span><small>MEAL LOGGED</small><strong>Balanced lunch</strong></span></div>
    <div className="float-card float-streak"><strong>12</strong><span><small>DAY STREAK</small><b>Keep it going</b></span></div>
  </div>;
}

export default function Home() {
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(appSchema)}} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(websiteSchema)}} />
    <nav className="nav shell"><a href="#top" className="brand" aria-label="Nexal home"><BrandMark /></a><div className="nav-links"><a href="#features">Features</a><a href="#how-it-works">How it works</a><a href="/ai-workout-planner">AI Workouts</a><a href="/ai-meal-planner">AI Meals</a></div><PlayButton compact placement="nav" /></nav>
    <section className="hero shell" id="top"><div className="hero-copy"><div className="eyebrow">BUILD THE BODY. OWN THE JOURNEY.</div><h1>AI workout and meal plans<br /><em>built around you.</em></h1><p>Nexal brings personalised workout plans, meal planning, calorie and macro tracking into one Android fitness app. Set your goals, follow your daily plan and see your progress in one place.</p><div className="hero-actions"><PlayButton placement="hero" /><a className="text-link" href="#how-it-works">See how Nexal works <span>↓</span></a></div><div className="trust-row"><p>Free core tracking. Premium AI planning. Available on Android.</p></div></div><PhonePreview /></section>
    <section className="signal-strip" aria-label="Nexal benefits"><div className="shell"><span>◆ PERSONALIZED DAILY TARGETS</span><span>◆ AI-POWERED PLANS</span><span>◆ MEANINGFUL PROGRESS</span></div></section>

    <section className="features-section shell" id="features">
      <div className="section-heading"><div><span className="section-kicker">ONE APP. YOUR WHOLE ROUTINE.</span><h2>Plan workouts. Track meals.<br /><em>See your progress.</em></h2></div><p>One place for the training and nutrition decisions you make every day.</p></div>
      <div className="feature-grid">
        <article className="feature-card dark-card"><span className="card-number">01</span><div className="feature-icon target-icon"><i /></div><h3>Calorie and macro tracking</h3><p>Log meals and see calories, protein, carbohydrates and fats against your daily targets. Keep nutrition beside your workouts. <a href="/calorie-macro-tracker">Explore the calorie and macro tracker</a>.</p><div className="macro-visual" aria-label="Illustrative macro target preview"><div><span>Protein</span><b>82%</b><i style={{"--bar":"82%"} as React.CSSProperties}/></div><div><span>Carbs</span><b>64%</b><i style={{"--bar":"64%"} as React.CSSProperties}/></div><div><span>Fats</span><b>71%</b><i style={{"--bar":"71%"} as React.CSSProperties}/></div></div></article>
        <article className="feature-card lime-card"><span className="card-number">02</span><div className="feature-icon sparkle-icon">✦</div><h3>AI workout and meal plans</h3><p>Nexal Premium creates <a href="/ai-workout-planner">AI workout plans</a> and <a href="/ai-meal-planner">AI meal plans</a> around your goals, schedule and food preferences.</p><div className="plan-stack" aria-label="Illustrative workout plan preview"><div><i>MON</i><span><small>STRENGTH</small><b>Upper body</b></span><em>32 min</em></div><div><i>TUE</i><span><small>RECOVERY</small><b>Mobility flow</b></span><em>18 min</em></div><div><i>WED</i><span><small>STRENGTH</small><b>Lower body</b></span><em>40 min</em></div></div></article>
        <article className="feature-card light-card"><span className="card-number">03</span><div className="feature-icon chart-icon"><i/><i/><i/></div><h3>Workout and progress tracking</h3><p>Record sessions and review training, nutrition and weight trends over time. See the habits behind your progress.</p><div className="spark-chart" aria-label="Illustrative four week progress chart"><span>4 week trend example</span><strong>+18%</strong><div className="chart-line"><i/><i/><i/><i/><i/><i/><i/><i/></div></div></article>
      </div>
    </section>

    <section className="how-section shell" id="how-it-works"><div className="how-intro"><span className="section-kicker">FROM GOAL TO DAILY ROUTINE</span><h2>How the Nexal AI fitness planner works</h2><p>Set a direction, build a plan that fits your life, and keep your progress visible.</p></div><div className="how-grid"><article><span>01</span><h3>Set your fitness goal</h3><p>Choose your goal, experience level and the routine that fits your current starting point.</p></article><article><span>02</span><h3>Build your plan</h3><p>With Nexal Premium, generate <a href="/ai-workout-planner">workout plans</a> and <a href="/ai-meal-planner">meal plans</a> shaped by your preferences and available training days.</p></article><article><span>03</span><h3>Track and adjust</h3><p>Log workouts and meals, check your calorie and macro targets, and review progress as your routine develops.</p></article></div><div className="how-action"><PlayButton placement="how_it_works" /></div></section>

    <section className="results-section" id="progress"><div className="shell results-grid">
      <div className="results-copy"><span className="section-kicker light">BUILT FOR CONSISTENCY</span><h2>Your progress.<br /><em>Made visible.</em></h2><p>Daily wins feel small. Nexal connects them into a clear story so you can see what is working and keep going.</p><ul><li><i>✓</i> Weekly progress and habit insights</li><li><i>✓</i> Clear calorie and macro trends</li><li><i>✓</i> Streaks that reward consistency</li></ul></div>
      <div className="analytics-card"><div className="analytics-top"><div><small>ILLUSTRATIVE MONTHLY OVERVIEW</small><h3>Your momentum</h3></div><span>Last 30 days⌄</span></div><div className="big-stat"><strong>86%</strong><span><b>↑ 14%</b> vs last month</span></div><div className="line-chart" aria-label="Illustrative rising monthly progress graph"><div className="grid-lines"><i/><i/><i/><i/></div><div className="trend-fill"/><div className="trend-line"><i/><i/><i/><i/><i/><i/></div></div><div className="chart-labels"><span>Week 1</span><span>Week 2</span><span>Week 3</span><span>Week 4</span></div><div className="metric-row"><div><i className="dot lime"/><span><small>WORKOUTS</small><b>18 completed</b></span></div><div><i className="dot green"/><span><small>NUTRITION</small><b>24 days on target</b></span></div></div></div>
    </div></section>

    <section className="premium-section shell" id="premium"><div className="premium-card"><div className="premium-glow"/><div className="premium-copy"><span className="section-kicker light">NEXAL PREMIUM</span><h2>Personalised AI workout<br />and <em>meal plans.</em></h2><p>Create a training and nutrition plan around your goals, schedule and preferences. Premium adds AI planning and food tools to Nexal&apos;s daily tracking experience.</p><div className="premium-pills"><span>✦ AI workout plans</span><span>✦ AI meal plans</span><span>✦ Barcode scanning</span></div><PlayButton placement="premium" /></div><div className="premium-phone"><div className="premium-screen"><span>YOUR WEEK</span><h3>Stronger, one day at a time.</h3>{["Upper body strength","Balanced meal plan","Lower body power"].map((item,index)=><div key={item} className="premium-row"><i>{index+1}</i><span><small>{index===1?"NUTRITION":"WORKOUT"}</small><b>{item}</b></span><em>{index===1?"View":"Start"}</em></div>)}</div></div></div></section>

    <section className="faq-section shell" id="faq"><div><span className="section-kicker">THE DETAILS</span><h2>Nexal app<br /><em>questions.</em></h2></div><div className="faq-list"><details open><summary>Is Nexal free to download on Android?<span>+</span></summary><p>Yes. Nexal is free to download on Google Play. Core meal, calorie, macro, workout and progress tracking are available without a subscription. Premium unlocks AI plans and advanced tools.</p></details><details><summary>Does Nexal generate both workout and meal plans?<span>+</span></summary><p>Nexal Premium generates workout and meal plans using your goals, schedule and preferences. Plans provide general fitness and wellness guidance, not medical advice.</p></details><details><summary>Can I track calories and macros in Nexal?<span>+</span></summary><p>Yes. Nexal tracks calories, protein, carbohydrates and fats alongside workouts and progress.</p></details><details><summary>Is Nexal available on iPhone?<span>+</span></summary><p>Nexal is currently available for Android through Google Play.</p></details></div></section>

    <section className="final-cta"><div className="shell"><BrandMark/><h2>Your next chapter<br />starts <em>today.</em></h2><p>Start with free tracking. Unlock AI plans when you are ready.</p><PlayButton placement="final_cta"/></div></section>
    <SiteFooter />
  </main>;
}
